### ISSUE TITLE
wrapper for tlmgr (texlive manager)?

### ISSUE THREAD

**Issue by anntzer** [icy/pacapt#106]
tlmgr (the TeXlive manager) is a bit a special case, as it is not a distro package manager; but it is still useful if one does not want to install the (usually huge, coarsely-grained) distro-provided packages.

Any chance in supporting it?  (Note that this would mean pacapt could be a frontend for multiple package managers on the same systems; a possibility would be e.g. to have `pacapt --backend=tlmgr ...` and let the user define whatever alias they want.)

**Comment by icy** [comment]
That's an excellent idea :) Let's see if we can support them.

**Comment by icy** [comment]
@anntzer Do you know how to install `tlmgr` on ArchLinux? I expect the binary file from `texlive-most` package unfortunately it's not true. Thx a lot.

**Comment by anntzer** [comment]
I think it is intentionally not packaged, likely because installs from it would always create conflicts with management by pacman.  I personally always install it manually (i.e., following https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-140003) into /usr/local (which is explicitly recommended for stuff "not managed by pacman"), as I don't like the coarse packages provided by the distro.

**Comment by anntzer** [comment]
Another non-distro package which would be nice to look at is conda (https://conda.io/docs/index.html).

I would be happy to help with the actual translation of commands for both tlmgr and conda, but will need help with setting up the machinery mentioned above (`--backend=...` or similar).

**Comment by icy** [comment]
Thanks again @anntzer . You have great idea. I will work on some experimental code this week.

**Comment by icy** [comment]
@anntzer There are at least two ways to support a `backend`:

* Using an option: `pacapt --backend=foo`
* Using special command name: `pacapt-foo`

What do you prefer?

**Comment by anntzer** [comment]
I think(?) the first one is better? (and suggest to the user to define their own shell aliases)  If you go for pacapt-foo, how exactly do you plan to distribute that?  I'd be a bit annoyed if installing pacapt directly gave me pacapt-dnf, pacapt-yum, and a bunch of irrelevant pacapts on my system (i.e. for package managers that I don't use).  (Not great for tab completion, for example.)

**Comment by icy** [comment]
The second way is easier for `pacapt`'s development work; it requires a few changes. This is because the major part of the script relies on `_PACMAN` variable as seen here https://github.com/icy/pacapt/blob/ng/lib/zz_main.sh#L32, and we can transform script name to a correct value for that variable. This can be done quickly. 

Adding a new option requires me to rewrite the argument parser. It also requires a few changes that may break the stability of the script. As you can see from `zz_main.sh`, the packager detection happens before the argument parser.

From a users' pov, here what I intend to do with the option (2):
* For the native system package manager, you don't need to install any `pacapt-foo` script. By using `pacapt` or its aliases, the script simply understands that the system package manager would be invoked.
* For ther non-system package manager (gem, conda, texlive,...) users have to create symlink `pacapt-gem`, `pacapt-conda`, `pacapt-texlive`, ... It's up to users to create those symlinks or not.
* I've never used `super completion`, and I think we still have completion with command name (not command options)
* (If we really like) we can also provide a resource file kind of `user default package manager`, e.g., `~/.pacapt.defaults` to specify the default behaviour of the script.

For option (1) I am still thinking if there is any other better way.

**Comment by anntzer** [comment]
I don't think my arguments for (1) above were particularly strong (I was just trying to pick between the two options), (2) is fine too; I didn't look into which one would have been more practical for you :)

**Comment by icy** [comment]
Ok let's talk about that in future, when we have better idea (E.g, when we rewrite the main/core part in go/d/python). 

I've had a simple implementation of the feature. You can see a sample library for `conda` here https://github.com/icy/pacapt/blob/ng/lib/conda.sh . 

You can start to add new `conda` support as below:

* Add new methods to `lib/conda.sh`
* Run `make pacapt.dev`
* Have a symbolic link `ln -s pacapt.dev pacapt-conda` (you only need to do this once)
* Enjoy `./pacapt-conda`

It's going well I will support better development resource (doc, Makefile, testings, ...)

Best,
