### ISSUE TITLE
Add -Rn & -Rns & -Rsn & -Syu

### ISSUE THREAD

**Issue by Red54** [icy/pacapt#13]
pacman -Rn => apt-get purge
pacman -Rns => apt-get --purge autoremove
pacman -Rsn => apt-get --purge autoremove

pacman -Syu => pacman -Suy
It seems that so many people are used to use -Syu

**Comment by xiongchiamiov** [comment]
I suppose that really the system should be overhauled a little so that the order of secondary arguments is not important - rather than creating a number of aliases (-Syu -> -Suy, etc.), the script should figure that out for itself.

The most elegant way I see of manually doing it is using fall-throughs, but apparently those were only added to bash [in version 4](http://stackoverflow.com/questions/12010686/case-statement-fallthrough), and it's probably not a good idea to restrict the systems this can run on just for that.

As for -Rn and -Rns, you should try adding them yourself!  Pacapt is designed in such a way that it's really quite easy to add new commands - just copy one of the existing commands and change the relevant parts.

**Comment by icy** [comment]
About `pacman -Syu` and `pacman -Suy`: Yes, I agree with _xiongchiamiov_. The order isn't important, and they are both working with the current version of `pacapt`. The `README` only mentions `pacman -Suy`, that's an issue of the documentation and I will fix it.

About `pacman -Rn` and `pacman -Rns`: I don't really know if the feature is the same in Arch and Debian. I will take a  look, but the idea is that we adopt the Arch's `pacman` features on other system, not vice versa.

**Comment by icy** [comment]
Hi,

I am sorry for my belated response.

According to [Rosetta](https://wiki.archlinux.org/index.php?title=Pacman_Rosetta), `apt-get autoremove` is equivalent to `pacman -Qdtq | pacman -Rs -`; this means that there isn't any single option in `pacman` that can work as same as `apt-get autoremove`. If we need to support the feature `autoremove`, we need some new option group to our `pacapt`.

Any ideas?

**Comment by icy** [comment]
Implemented in 
- https://github.com/icy/pacapt/commit/86fba36138360c254d791bb360007fe178dfa9a6 (option detection)
- https://github.com/icy/pacapt/commit/40a1348309a10c18648f393c710ee214a911558c (debian)
